apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-certmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  destination:
    name: kind-test-1
    namespace: cert-manager
  sources:
    # Source 1: JIT RBAC (ClusterRole + ClusterRoleBinding)
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-certmanager
        patches:
          - target:
              kind: ClusterRole
              name: PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-certmanager
          - target:
              kind: ClusterRoleBinding
              name: PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-certmanager
              - op: replace
                path: /roleRef/name
                value: argocd-manager-certmanager
    
    # Source 2: PreDelete Hook (creates deletion RBAC before app removal)
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac-predelete
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-certmanager
        patches:
          - target:
              kind: Job
              name: PLACEHOLDER-create-deletion-rbac
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-certmanager-create-deletion-rbac
              - op: replace
                path: /spec/template/spec/containers/0/env/1/value
                value: argocd-manager-certmanager-deletion
              - op: replace
                path: /spec/template/spec/containers/0/env/2/value
                value: argocd-manager-certmanager-deletion
          - target:
              kind: ClusterRoleBinding
              name: jit-rbac-predelete-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-predelete-k8s-spb2-backend1-certmanager
    
    # Source 3: Job wave 99 (marks sync as completed)
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-certmanager
        patches:
          - target:
              kind: Job
              name: PLACEHOLDER-mark-completed
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-certmanager-mark-completed
    
    # Source 4: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: cert-manager
      helm:
        releaseName: k8s-spb2-backend2-certmanager
        values: |
          installCRDs: true
          startupapicheck:
           enabled: false
