apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: argocd-manager-kyverno
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: argocd-manager-kyverno
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: jit-rbac-marker-k8s-spb2-backend1-kyverno
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: jit-rbac-marker-k8s-spb2-backend1-kyverno
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: batch
      kind: Job
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: kyverno
  sources:
    # Source 1: JIT RBAC (ClusterRole + ClusterRoleBinding)
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: kyverno-role.yaml
    # Source 2: Job wave 99
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-kyverno
        patches:
          - target:
              kind: ServiceAccount
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
          - target:
              kind: ClusterRole
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
          - target:
              kind: ClusterRoleBinding
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
              - op: replace
                path: /roleRef/name
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
              - op: replace
                path: /subjects/0/name
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
              - op: replace
                path: /subjects/0/namespace
                value: kyverno
          - target:
              kind: Job
              name: PLACEHOLDER-mark-completed
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-kyverno-mark-completed
              - op: replace
                path: /spec/template/spec/serviceAccountName
                value: jit-rbac-marker-k8s-spb2-backend1-kyverno
              - op: replace
                path: /spec/template/spec/containers/0/env/0/value
                value: k8s-spb2-backend1-kyverno
    # Source 3: Helm chart
    - repoURL: 'https://kyverno.github.io/kyverno/'
      targetRevision: 3.2.7
      chart: kyverno
      helm:
        releaseName: kyverno
        values: |
          crds:
            install: true
            groups:
              kyverno:
                clusterpolicies: true
                policies: true
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true
          webhooksCleanup:
            image:
              registry: docker.io
              repository: bitnami/kubectl
              tag: 1.28
          features:
            policyExceptions:
              enabled: true
          cleanupJobs:
            admissionReports:
              image:
                registry: docker.io
                repository: bitnami/kubectl
                tag: 1.28
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 64Mi
                  cpu: 50m
            clusterAdmissionReports:
              image:
                registry: docker.io
                repository: bitnami/kubectl
                tag: 1.28
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 64Mi
                  cpu: 50m
            updateRequests:
              image:
                registry: docker.io
                repository: bitnami/kubectl
                tag: 1.28
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 64Mi
                  cpu: 50m
            ephemeralReports:
              image:
                registry: docker.io
                repository: bitnami/kubectl
                tag: 1.28
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 64Mi
                  cpu: 50m
            clusterEphemeralReports:
              image:
                registry: docker.io
                repository: bitnami/kubectl
                tag: 1.28
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 64Mi
                  cpu: 50m
          admissionController:
            initContainer:
              image:
                registry: ghcr.io
                repository: kyverno/kyvernopre
                tag: v1.12.5
            container:
              extraArgs:
                loggingFormat: json
              image:
                registry: ghcr.io
                repository: kyverno/kyverno
                tag: v1.12.5
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
                requests:
                  memory: 128Mi
                  cpu: 100m
          backgroundController:
            rbac:
              clusterRole:
                extraResources:
                  - apiGroups:
                      - ""
                    resources:
                      - namespaces
                    verbs:
                      - patch
                      - update
            extraArgs:
              loggingFormat: json
            image:
              registry: ghcr.io
              repository: kyverno/background-controller
              tag: v1.12.5
            resources:
              limits:
                memory: 1Gi
                cpu: 500m
              requests:
                memory: 128Mi
                cpu: 100m
          cleanupController:
            rbac:
              clusterRole:
                extraResources:
                  - apiGroups:
                      - ""
                    resources:
                      - namespaces
                    verbs:
                      - delete
            extraArgs:
              loggingFormat: json
            image:
              registry: ghcr.io
              repository: kyverno/cleanup-controller
              tag: v1.12.5
            resources:
              limits:
                memory: 256Mi
                cpu: 250m
              requests:
                memory: 64Mi
                cpu: 50m
          reportsController:
            resources:
              limits:
                memory: 1Gi
                cpu: 1
              requests:
                cpu: 100m
                memory: 128Mi
            extraArgs:
              loggingFormat: json
            image:
              registry: ghcr.io
              repository: kyverno/reports-controller
              tag: v1.12.5
          tolerations: []
          nodeSelector: {}
          affinity: {}
