apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: false
  project: k8s-spb2-backend1
  destination:
    name: k8s-spb2-backend1
    namespace: kyverno
  source:
    repoURL: 'https://artifactory.playteam.ru:443/artifactory/helm/'
    targetRevision: 3.2.7
    chart: kyverno
    helm:
      releaseName: kyverno
      valuesObject:
        webhooksCleanup:
          image:
            registry: registry.playteam.ru
            repository: kubectl
            tag: 1.26.4
        features:
          policyExceptions:
            enabled: true
        cleanupJobs:
          admissionReports:
            image:
              registry: registry.playteam.ru
              repository: kubectl
              tag: 1.26.4
            resources:
              limits:
                memory: 1G
                cpu: 1
              requests:
                memory: 128Mi
                cpu: 100m
          clusterAdmissionReports:
            image:
              registry: registry.playteam.ru
              repository: kubectl
              tag: 1.26.4
            resources:
              limits:
                memory: 1G
                cpu: 1
              requests:
                memory: 128Mi
                cpu: 100m
          updateRequests:
            image:
              registry: registry.playteam.ru
              repository: kubectl
              tag: 1.26.4
            resources:
              limits:
                memory: 1G
                cpu: 1
              requests:
                memory: 128Mi
                cpu: 100m
          ephemeralReports:
            image:
              registry: registry.playteam.ru
              repository: kubectl
              tag: 1.26.4
            resources:
              limits:
                memory: 1G
                cpu: 1
              requests:
                memory: 128Mi
                cpu: 100m
          clusterEphemeralReports:
            image:
              registry: registry.playteam.ru
              repository: kubectl
              tag: 1.26.4
            resources:
              limits:
                memory: 1G
                cpu: 1
              requests:
                memory: 128Mi
                cpu: 100m
        admissionController:
          initContainer:
            image:
              registry: registry.playteam.ru
              repository: kyverno/kyvernopre
              tag: v1.12.5
          container:
            extraArgs:
              loggingFormat: json
            image:
              registry: registry.playteam.ru
              repository: kyverno
              tag: v1.12.5
            resources:
              limits:
                memory: 1G
                cpu: 1
        backgroundController:
          rbac:
            clusterRole:
              extraResources:
                - apiGroups:
                    - ""
                  resources:
                    - namespaces
                  verbs:
                    - patch
                    - update
          extraArgs:
            loggingFormat: json
          image:
            registry: registry.playteam.ru
            repository: kyverno/background-controller
            tag: v1.12.5
          resources:
            limits:
              memory: 4G
              cpu: 1
        cleanupController:
          rbac:
            clusterRole:
              extraResources:
                - apiGroups:
                    - ""
                  resources:
                    - namespaces
                  verbs:
                    - delete
          extraArgs:
            loggingFormat: json
          image:
            registry: registry.playteam.ru
            repository: kyverno/cleanup-controller
            tag: v1.12.5
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
        reportsController:
          resources:
            limits:
              memory: 4G
              cpu: 2
            requests:
              cpu: 100m
              memory: 128Mi
          extraArgs:
            loggingFormat: json
          image:
            registry: registry.playteam.ru
            repository: kyverno/reports-controller
            tag: v1.12.5
        tolerations:
          - key: "node-role.kubernetes.io/infr"
            operator: "Exists"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: "node-role.kubernetes.io/infr"
                      operator: "Exists"
