apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: false
  project: k8s-spb2-backend1
  destination:
    name: k8s-spb2-backend1
    namespace: kyverno
  source:
    repoURL: 'https://artifactory.playteam.ru:443/artifactory/helm/'
    targetRevision: 2.24.2
    chart: policy-reporter
    helm:
      releaseName: policy-reporter
      valuesObject:
        logging:
          encoding: json
        image:
          registry: registry.playteam.ru
          tag: 2.24.1
        monitoring:
          enabled: true
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 75Mi
            cpu: 5m
        tolerations:
          - key: "node-role.kubernetes.io/infr"
            operator: "Exists"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                    - key: "node-role.kubernetes.io/infr"
                      operator: "Exists"
