apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: argocd-manager-velero
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: argocd-manager-velero
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: jit-rbac-marker-k8s-spb2-backend1-velero
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: jit-rbac-marker-k8s-spb2-backend1-velero
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
  destination:
    namespace: velero
    name: kind-test-1
  sources:
    # Source 1: JIT RBAC (ClusterRole + ClusterRoleBinding)
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac-roles
      directory:
        include: velero-role.yaml
    # Source 2: Job wave 99
    - repoURL: 'https://github.com/nomad-mrkn/0zargo.git'
      targetRevision: HEAD
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: k8s-spb2-backend1-velero
        patches:
          - target:
              kind: ServiceAccount
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-velero
          - target:
              kind: ClusterRole
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-velero
          - target:
              kind: ClusterRoleBinding
              name: jit-rbac-marker-PLACEHOLDER
            patch: |-
              - op: replace
                path: /metadata/name
                value: jit-rbac-marker-k8s-spb2-backend1-velero
              - op: replace
                path: /roleRef/name
                value: jit-rbac-marker-k8s-spb2-backend1-velero
              - op: replace
                path: /subjects/0/name
                value: jit-rbac-marker-k8s-spb2-backend1-velero
              - op: replace
                path: /subjects/0/namespace
                value: velero
          - target:
              kind: Job
              name: PLACEHOLDER-mark-completed
            patch: |-
              - op: replace
                path: /metadata/name
                value: k8s-spb2-backend1-velero-mark-completed
              - op: replace
                path: /spec/template/spec/serviceAccountName
                value: jit-rbac-marker-k8s-spb2-backend1-velero
              - op: replace
                path: /spec/template/spec/containers/0/env/0/value
                value: k8s-spb2-backend1-velero
    # Source 3: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: velero
      helm:
        releaseName: k8s-spb2-backend1-velero
        values: |
          rbac:
            create: true
          configuration:
            backupStorageLocation:
              prefix: test/kind-test-1
          schedules:
            k8s-spb2-backend1:
              disabled: true
          excludedResources:
          - horizontalpodautoscalers.autoscaling
          - secrets
          credentials:
            useSecret: true
            existingSecret: null
            secretContents:
              cloud: |
                [default]
                aws_access_key_id=dummy
                aws_secret_access_key=dummy
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          restic:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          tolerations: []
          nodeSelector: {}
          affinity: {}
          serviceMonitor:
            enabled: false
          prometheusRule:
            enabled: false
