---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jit-rbac-marker
  annotations:
    argocd.argoproj.io/sync-wave: "98"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jit-rbac-marker
  annotations:
    argocd.argoproj.io/sync-wave: "98"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jit-rbac-marker-PLACEHOLDER
  annotations:
    argocd.argoproj.io/sync-wave: "98"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jit-rbac-marker
subjects:
  - kind: ServiceAccount
    name: jit-rbac-marker
    namespace: cert-manager
