apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-certmanager
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
      - certificaterequests/status
      - certificaterequests/finalizers
      - certificates/status
      - certificates/finalizers
      - clusterissuers/status
      - issuers/status
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders
      - orders/status
      - orders/finalizers
      - challenges
      - challenges/status
      - challenges/finalizers
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/status
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    verbs: ["sign"]
  
  - apiGroups: ["cert-manager.io"]
    resources: ["signers"]
    verbs: ["approve"]
  
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - gateways/finalizers
      - httproutes
      - httproutes/finalizers
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - ingresses/finalizers
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  
  - apiGroups: ["route.openshift.io"]
    resources: ["routes/custom-host"]
    verbs: ["create", "delete"]
  
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - events
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "list", "get", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: PLACEHOLDER
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-certmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: PLACEHOLDER-pre-delete
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-certmanager
    jit-rbac/hook: pre-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system