apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Force=true,SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/sync-status: "in-progress"
    jit-rbac/app: PLACEHOLDER
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
      - certificaterequests/status
      - certificaterequests/finalizers
      - certificates/status
      - certificates/finalizers
      - clusterissuers/status
      - issuers/status
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders
      - orders/status
      - orders/finalizers
      - challenges
      - challenges/status
      - challenges/finalizers
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "services", "configmaps", "secrets", "pods", "events"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "list", "get", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Force=true,SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/sync-status: "in-progress"
    jit-rbac/app: PLACEHOLDER
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: PLACEHOLDER
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
