apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: PLACEHOLDER-deletion
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
    jit-rbac/phase: deletion
rules:
  # CRDs deletion
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # cert-manager resources deletion
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
      - certificaterequests/status
      - certificaterequests/finalizers
      - certificates/status
      - certificates/finalizers
      - clusterissuers/status
      - issuers/status
    verbs: ["delete", "get", "list", "patch", "update"]
  
  - apiGroups: ["acme.cert-manager.io"]
    resources:
      - orders
      - orders/status
      - orders/finalizers
      - challenges
      - challenges/status
      - challenges/finalizers
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Webhooks deletion
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Apps deletion
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Core resources deletion
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - persistentvolumeclaims
    verbs: ["delete", "get", "list", "patch", "update"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # RBAC deletion
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Batch resources deletion
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Leases deletion
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["delete", "get", "list", "patch", "update"]
  
  # Events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: PLACEHOLDER-deletion
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
    jit-rbac/phase: deletion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: PLACEHOLDER-deletion
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system

