apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-fluent-bit
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-fluent-bit
rules:
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - pods/log
      - events
      - endpoints
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
  
  # RBAC rights for ArgoCD kubectl auth reconcile (namespace-scoped only)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["get", "list", "create", "update", "patch"]
  
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheusrules
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: ["autoscaling.k8s.io"]
    resources:
      - verticalpodautoscalers
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "get", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-fluent-bit
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-fluent-bit
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system
