apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-haproxy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-haproxy
rules:
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - serviceaccounts
      - configmaps
      - secrets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-haproxy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-haproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-haproxy
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system

