apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-kyverno
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "patch", "get", "list", "watch"]

  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - pods
      - endpoints
      - events
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments/scale
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - services
      - ingresses
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]