apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-velero
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-velero
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
      - configmaps
      - secrets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["velero.io"]
    resources:
      - backups
      - restores
      - backupstoragelocations
      - volumesnapshotlocations
      - schedules
      - downloadrequests
      - deletebackuprequests
      - podvolumebackups
      - podvolumerestores
      - serverstatusrequests
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - prometheusrules
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["operator.victoriametrics.com"]
    resources:
      - vmservicescrapes
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-velero
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-velero
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system

