apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-x509
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: ""
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-x509
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - serviceaccounts
      - services
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources:
      - namespaces
      - secrets
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-x509
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: ""
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: k8s-spb2-backend1-x509
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-x509
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system

