apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-watcher
rules:
  - apiGroups: ["admissionregistration.k8s.io", "apiextensions.k8s.io", "apiregistration.k8s.io", "apps", "autoscaling.k8s.io", "autoscaling", "batch", "cert-manager.io", "extensions", "flowcontrol.apiserver.k8s.io", "grafana.integreatly.org", "jaegertracing.io", "keda.sh", "monitoring.coreos.com", "networking.k8s.io", "operator.victoriametrics.com", "policy", "rbac.authorization.k8s.io", "ricoberger.de", "", "velero.io", "storage.k8s.io"]
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    - validatingadmissionpolicybindings
    - validatingadmissionpolicies
    - apiservices
    - customresourcedefinitions
    - daemonsets
    - deployments
    - statefulsets
    - controllerrevisions
    - verticalpodautoscalers
    - horizontalpodautoscalers
    - certificates
    - issuers
    - ingresses
    - flowschemas
    - prioritylevelconfigurations
    - grafanadashboards
    - jaegers
    - scaledobjects
    - podmonitors
    - prometheusrules
    - servicemonitors
    - ingressclasses
    - networkpolicies
    - servicecidrs
    - ipaddresses
    - vmagents
    - vmnodescrapes
    - vmpodscrapes
    - vmservicescrapes
    - poddisruptionbudgets
    - podsecuritypolicies
    - rolebindings
    - roles
    - vaultsecrets
    - configmaps
    - endpoints
    - serviceaccounts
    - services
    - replicationcontrollers
    - nodes
    - limitranges
    - resourcequotas
    - podtemplates
    - backupstoragelocations
    - schedules
    - volumesnapshotlocations
    - persistentvolumeclaims
    - persistentvolumes
    - storageclasses
    - csistoragecapacities
    - volumeattributesclasses
    - csinodes
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "list"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch", "patch"]
  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["bind", "get", "update", "patch", "create", "escalate", "list", "watch"]
  
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "list", "get", "watch", "update", "patch"]
  
  - apiGroups: [""]
    resources: ["pods", "configmaps", "replicationcontrollers"]
    verbs: ["delete", "get", "list", "watch"]
  
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["update", "patch"]
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
