---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jit-rbac-predelete
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
    jit-rbac/phase: deletion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jit-rbac-predelete
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jit-rbac-predelete-PLACEHOLDER
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
    jit-rbac/phase: deletion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jit-rbac-predelete
subjects:
  - kind: ServiceAccount
    name: jit-rbac-predelete
    namespace: cert-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER-create-deletion-rbac
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
    jit-rbac/app: PLACEHOLDER
    jit-rbac/phase: deletion
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argo-jit-rbac
        jit-rbac/app: PLACEHOLDER
        jit-rbac/phase: deletion
    spec:
      serviceAccountName: jit-rbac-predelete
      restartPolicy: Never
      containers:
      - name: create-deletion-rbac
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JIT_RBAC_APP
          value: PLACEHOLDER
        - name: ROLE_NAME
          value: PLACEHOLDER-deletion
        - name: BINDING_NAME
          value: PLACEHOLDER-deletion
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -euo pipefail
            echo "========================================="
            echo "Creating deletion RBAC for ${JIT_RBAC_APP}"
            echo "Started at $(date -u +%FT%TZ)"
            echo "========================================="
            
            # Create ClusterRole for deletion
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: ${ROLE_NAME}
              labels:
                app.kubernetes.io/part-of: argo-jit-rbac
                jit-rbac/app: ${JIT_RBAC_APP}
                jit-rbac/phase: deletion
            rules:
              - apiGroups: ["apiextensions.k8s.io"]
                resources: ["customresourcedefinitions"]
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["cert-manager.io"]
                resources:
                  - certificates
                  - certificaterequests
                  - issuers
                  - clusterissuers
                  - certificaterequests/status
                  - certificaterequests/finalizers
                  - certificates/status
                  - certificates/finalizers
                  - clusterissuers/status
                  - issuers/status
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["acme.cert-manager.io"]
                resources:
                  - orders
                  - orders/status
                  - orders/finalizers
                  - challenges
                  - challenges/status
                  - challenges/finalizers
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["admissionregistration.k8s.io"]
                resources:
                  - mutatingwebhookconfigurations
                  - validatingwebhookconfigurations
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["apps"]
                resources:
                  - deployments
                  - replicasets
                  - daemonsets
                  - statefulsets
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: [""]
                resources:
                  - serviceaccounts
                  - services
                  - configmaps
                  - secrets
                  - pods
                  - persistentvolumeclaims
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: [""]
                resources: ["namespaces"]
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["rbac.authorization.k8s.io"]
                resources:
                  - roles
                  - rolebindings
                  - clusterroles
                  - clusterrolebindings
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["batch"]
                resources: ["jobs", "cronjobs"]
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: ["coordination.k8s.io"]
                resources: ["leases"]
                verbs: ["delete", "get", "list", "patch", "update"]
              - apiGroups: [""]
                resources: ["events"]
                verbs: ["create", "list"]
            EOF
            
            if [ $? -eq 0 ]; then
              echo "✓ ClusterRole ${ROLE_NAME} created successfully"
            else
              echo "✗ Failed to create ClusterRole"
              exit 1
            fi
            
            # Create ClusterRoleBinding for deletion
            cat <<EOF | kubectl apply -f -
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: ${BINDING_NAME}
              labels:
                app.kubernetes.io/part-of: argo-jit-rbac
                jit-rbac/app: ${JIT_RBAC_APP}
                jit-rbac/phase: deletion
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: ${ROLE_NAME}
            subjects:
              - kind: ServiceAccount
                name: argocd-manager
                namespace: kube-system
            EOF
            
            if [ $? -eq 0 ]; then
              echo "✓ ClusterRoleBinding ${BINDING_NAME} created successfully"
            else
              echo "✗ Failed to create ClusterRoleBinding"
              exit 1
            fi
            
            echo "========================================="
            echo "Deletion RBAC created successfully"
            echo "Role: ${ROLE_NAME}"
            echo "Binding: ${BINDING_NAME}"
            echo "Completed at $(date -u +%FT%TZ)"
            echo "========================================="
            echo ""
            echo "Application deletion can now proceed safely."
            echo "Remember to manually clean up deletion RBAC after application is removed:"
            echo "  kubectl delete clusterrole ${ROLE_NAME}"
            echo "  kubectl delete clusterrolebinding ${BINDING_NAME}"

